name: Test Model

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: yarn install --immutable
      - run: yarn test
        working-directory: model
      - run: yarn codecov
        name: Upload coverage
        working-directory: model
